### ISSUE TITLE
谁愿意做第一个小白鼠？

### ISSUE THREAD

**Issue by parcool** [Xiaofei-it/Shelly#23]
相对于RxJava来说，文档与热度与成熟度都还不够，生产环境中没人敢用。不过，敢写这么一个库是非常值得支持与表扬的，一起期待在后面的发展吧。嘿

**Comment by Xiaofei-it** [comment]
这个不是RxJava的替代品，特色和用法与RxJava都不一样，只是API相似，具体请看理论部分的阐述。

另外，我们工程里的一部分代码已经使用了。
